name: Codespell

on:
  pull_request: {}
  push: {}

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Codespell
        uses: codespell-project/actions-codespell@v1
     